### ISSUE TITLE
short kmer alignments with edit distance > 2?

### ISSUE THREAD

**Issue by JokingHero** [raja-appuswamy/accel-align-release#3]
Hi,

Thanks for the tool, I believe it will become a popular alternative to what is out there. I wanted to ask whether its possible to align really short sequences - 23bp, but with edit distance of 3? Is it possible to get all possible matches to the genome?

Best,
Kornel

**Comment by raja-appuswamy** [comment]
Hello Kornel,
  Ofcourse. In principle it should be possible to use accel-align for such short sequences also. You can try experimenting with short kmer lengths (try 7 first, then 5 if 7 doesn't work). You should be able to index the reference genome and run accel align with this kmer length. Things will get slower though depending on the size of the reference. Please let us know if this works, or if you run into any problems. We'll be happy to help out. 

Regards,
Raja

**Comment by JokingHero** [comment]
Not sure what I am doing wrong, but I suspect there is a bug.

Command:
docker run -i rajaappuswamy/accel-align ./accindex-x86-64 -l 7 -m hg38v34.fa

Result:
Using kmer length 7 and step size 1
Loading ref

This takes no time to run and then program quits for some reason, without any error reported, also there is no .hash being created.

**Comment by JokingHero** [comment]
Never-mind my previous post, it was my docker problems, but now I am running out of the hashing limit it seems, is there anything I can do about it?

/DATA# /opt/accel-align-release/accindex-x86-64 -l 7 hg38v34.fa 
Using kmer length 7 and step size 1
Loading ref
genome	3099750718
hashing :limit = 3099750712, vsz = 3099750712
hash	3099750712
sorting
Killed

**Comment by raja-appuswamy** [comment]
This is happening because by default the indexing code uses parallel sort which takes more memory. There is a -m flag which you should try using that will reduce memory consumption. 
So this: /opt/accel-align-release/accindex-x86-64 -m -l 7 hg38v34.fa
The index will take a longer to build as sorting will be single threaded, but it should work if your system has < 32GB.

Sorry about the abrupt crash without a warning. We'll fix the code so that it puts out a more descriptive message.
